sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /cam3d/depth_registered/points
    max_range: 3.0
    padding_offset: 0.02
    padding_scale: 1
    point_subsample: 1
